server:
  port: 10110
  servlet:
    context-path: /${artifactId}

# pulsar配置
pulsar:
  # pulsar服务端地址
  url: pulsar://192.168.5.141:16650
  admin-url: http://192.168.5.144:16680
  token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiJ9.me_HN1DI9hgM8-MbmYtHogXyJ8vtkbffiiw-KOALKsgBgsQ22uUWwH7EfsCfPEbKWor39fQ_wqS6q2AwwUON0Qrjq1u9WW2Vu4U52voSOofywSUqGaodAsAwxygHu-EQB53p8fr2UFA5jtgod4H5bfKI6Ikrm_ah2LdvfvH7omfoEwyssVUjMCxQcHiVofqe7VMZxCzlVgL2vCXZj8tTuEtZa9hJ2K5hSI5abDgkV6hp_2fBoA3zLelnKGblP2npEEtaIr8jY0O_q7yKO0LV16qh7iXUN946QJxBEKkbP2bd4Fi2Ur0t2ERiQ1iP1Yx6vdAIYXMWUpdhxEwWA0Ze5w
#  token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0LXVzZXIiLCJleHAiOjE2NzQxNzY0NzB9.Ouw_AHENcdAb4r-TfE1rGJj-cudykltDrjjV-MIX1zOVYpyoPsww6lRNl47RlpPG9J82rB5VYCKlSF3wnVmOMDAoHLYWTXpXC-WVyyhiUbUHJHb4EHi3lZZcd3rRUN6TwK015hMYitb9CW-2HLk4sDs9jSU00ebriRjqvETTL8JiNYgw3y_mG7PWy1otxv3riS7SsPXt4wn3MlsOSCDyTUfAQHTX_NeZ9jGqWXs-zqBM9ipxKZueilghKbjKfoDB5D1tGpehTrhhRvMLMn7xDQHkM5f7utFrhmKSY8oV_Qp1S2aAiCc1ULoTHPXBm-AOKhHUMQeadsVWtrqklwftvQ
  producer:
    topic: test1
  consumer:
    # 多个topic以逗号分隔
    topic: test1,test2
    # 消费者组
    subscription: testGroup



swagger:
  enabled: true
  print-init: true
  docket:
    base-package: com.cn.boot.sample.pulsar.controller
    group-name: ${artifactId}
    path-selectors:
      exclude-patterns: [ /error ]
    api-info:
      contact:
        name: ChenNan
        email: 327919006@qq.com
        url: https://gitee.com/NuLiing
      title: ${artifactId}
      description: ${artifactId}-接口文档
      license: Apache License, Version 2.0
      license-url: https://www.apache.org/licenses/LICENSE-2.0.html
      version: ${project.version}
      terms-of-service-url: https://gitee.com/NuLiing
    response-message-language: cn
