# 开发环境配置
server:
  port: 10084

spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/boot_sample?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: chennan
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

swagger:
  enabled: true
  print-init: true
  docket:
    base-package: com.cn.boot.sample.server.mp.controller
    group-name: ${artifactId}
    path-selectors:
      exclude-patterns: [ /error ]
    api-info:
      contact:
        name: ChenNan
        email: 327919006@qq.com
        url: https://gitee.com/NuLiing
      title: ${artifactId}
      description: ${artifactId}-接口文档
      license: Apache License, Version 2.0
      license-url: https://www.apache.org/licenses/LICENSE-2.0.html
      version: ${project.version}
      terms-of-service-url: https://gitee.com/NuLiing
    response-message-language: cn