spring:
  profiles:
    active: @profileActive@


mybatis-plus:
  typeAliasesPackage: com.cn.boot.sample.dal.mp.model.po
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false #是否开启二级缓存
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler #枚举处理
  global-config:
    banner: false #控制是否在控制台打印 MyBatis-Plus 的 LOGO
    db-config:
      id-type: ASSIGN_ID #ID类型，默认雪花ID
      insert-strategy: not_null #默认：仅在字段值不为 NULL 时插入该字段
      update-strategy: not_null #默认：仅在字段值不为 NULL 时更新该字段,ALWAYS:无论字段是否为空都更新