server:
  port: 10102

spring:
  graphql:
    schema:
      locations: classpath:graphql/
      printer:
        # The GraphQL schema can be viewed over HTTP at "/graphql/schema"
        enabled: true

