server:
  port: 10107
  servlet:
    context-path: /${artifactId}

spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://192.168.5.156:9030
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    druid:
      initial-size: 5    #初始化连接个数
      min-idle: 5        #最小空闲连接个数
      max-active: 100    #最大连接个数
      max-wait: 60000    #获取连接时最大等待时间，单位毫秒。
      validation-query: select 1

mybatis:
  typeAliasesPackage: com.cn.boot.sample.doris.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

swagger:
  enabled: true
  print-init: true
  docket:
    base-package: com.cn.boot.sample.doris.controller
    group-name: ${artifactId}
    path-selectors:
      exclude-patterns: [/error]
    api-info:
      contact:
        name: ChenNan
        email: 327919006@qq.com
        url: https://gitee.com/NuLiing
      title: ${artifactId}
      description: ${artifactId}-接口文档
      license: Apache License, Version 2.0
      license-url: https://www.apache.org/licenses/LICENSE-2.0.html
      version: ${project.version}
      terms-of-service-url: https://gitee.com/NuLiing
    response-message-language: cn
