server:
  port: 10107
  servlet:
    context-path: /${artifactId}

spring:
  # 数据库连接配置
  datasource:
#    driver-class-name: com.taosdata.jdbc.TSDBDriver
#    url: jdbc:TAOS://h1.dev.com:6030/demo?user=root&password=taosdata
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    url: jdbc:TAOS-RS://h1.dev.com:6041/demo?user=root&password=taosdata&charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5    #初始化连接个数
      min-idle: 5        #最小空闲连接个数
      max-active: 10     #最大连接个数
      max-wait: 60000    #获取连接时最大等待时间，单位毫秒。
      validation-query: select server_status()

mybatis:
  typeAliasesPackage: com.cn.boot.sample.tdengine.model.po
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

swagger:
  enabled: true
  print-init: true
  docket:
    base-package: com.cn.boot.sample.tdengine.controller
    group-name: ${artifactId}
    path-selectors:
      exclude-patterns: [/error]
    api-info:
      contact:
        name: ChenNan
        email: 327919006@qq.com
        url: https://gitee.com/NuLiing
      title: ${artifactId}
      description: ${artifactId}-接口文档
      license: Apache License, Version 2.0
      license-url: https://www.apache.org/licenses/LICENSE-2.0.html
      version: ${project.version}
      terms-of-service-url: https://gitee.com/NuLiing
    response-message-language: cn
