server:
  port: 10099
  servlet:
    context-path: /${artifactId}
spring:
  elasticsearch:
    rest:
      uris: http://192.168.5.131:15591
      username: elastic
      password: kXu418c7boV8Y096zTOA1lo6
  servlet:
    multipart:
      max-file-size: 10MB

swagger:
  enabled: true
  print-init: true
  docket:
    base-package: com.cn.boot.sample.es.controller
    group-name: ${artifactId}
    path-selectors:
      exclude-patterns: [/error]
    api-info:
      contact:
        name: ChenNan
        email: 327919006@qq.com
        url: https://gitee.com/NuLiing
      title: ${artifactId}
      description: ${artifactId}-接口文档
      license: Apache License, Version 2.0
      license-url: https://www.apache.org/licenses/LICENSE-2.0.html
      version: ${project.version}
      terms-of-service-url: https://gitee.com/NuLiing
    response-message-language: cn